# Generated by Django 3.1.7 on 2021-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/BC/images/emptycart.png', upload_to='static/userimage'),
        ),
    ]
