# Generated by Django 3.1.7 on 2021-04-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20210401_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(upload_to='static/userimage'),
        ),
    ]
