# Generated by Django 3.1.7 on 2021-04-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20210407_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='locality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='state',
            field=models.CharField(choices=[('BAGMATI', 'BAGMATI'), ('GANDAKI', 'GANDAKI'), ('LUMBINI', 'LUMBINI'), ('KARNALI ', 'KARNALI'), ('SUDHURPASCHIM ', 'SUDHURPASCHIM')], max_length=50, null=True),
        ),
    ]
