# Generated by Django 3.1.7 on 2021-04-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210408_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='state',
        ),
    ]
