# Generated by Django 3.1.7 on 2021-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210416_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/BBC/images/icon/moon.png', upload_to='static/userimage'),
        ),
    ]
