# Generated by Django 3.1.7 on 2021-03-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customer_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
