# Generated by Django 3.1.7 on 2021-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_customer_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'FULLFACE'), ('H', 'Halfface'), ('B', 'BOOTS'), ('W', 'WEARS')], max_length=2),
        ),
    ]
